### PR TITLE
build: add pre-commits

### PR DESCRIPTION
**Pull request by 12rambau**
I don't know if you are aware of [pre-commits](https://pre-commit.com/), the idea is to run the linting, style rules on every git commit call. 

I included: 
- black the famous Python linter: 
- ruff: a super fast implementation of all PEP rules: 
- nbstripout: remove all outputs from notebook to simplify their versionning
- prettier, for anything that is not a .py file
- doc8, like ruff but for the soon to come Sphinx documentation
- licenceChek (not yet active) to check the compatibility of your license with the one from the dependencies

I included some ruff rules about docstring style and feel free to change it if your prefer numpy-style

I deactivated the docstring check but that would be nice to keep it in mind while coding. Cost nothing to do it upfront and save hours when debugging is needed

These hooks are also tested in a rudimentary Github Action to ensure they are respected in PR (when people only use the Github interface for example)

### CODE REVIEW

**Comment by 12rambau** [comment]
for the demo.ipynb I would like to include it in the documentation using mystnb (which execute the cells at build time) and add 2 links to open it in either binder or colab. 

Easy to maintain for us (no output in the file), easy to reuse for readers. I have an example in one of my other libs (it's quantum computing so very unrelated): https://pyqutree.readthedocs.io/en/latest/examples/demo.html

what do you think ?

**Comment by 12rambau** [comment]
> If we add ipython as a regular dependency, I think we should make sure to include the minimum possible required version.

I think version number is something that will be easier to pin when the test and actions will be up and running be as smooth as you think and I'll try to create environment check asap

**Comment by santiagobasulto** [comment]
Alright, let's give it a test! I'm gonna merge this one so I can finish pushing a few tests and design changes that I have pending.

**Comment by santiagobasulto** [comment]
@12rambau I commented out `nbstripout` for now so I can leave `Demo.ipynb` as documentation. But I like the idea of including `mystnb`, so I'll focus on documentation in the next few days.

**Comment by 12rambau** [comment]
no problem, I can update #8 and #7 to have a working framework. In the meantime could you create a project on ReadThedocs website and enable build on PR so that I test the result automatically (Only the owner of the repo can do that) ?

**Pull request merged**
